### ISSUE TITLE
Al descargar la plantilla no encuentra archivo

### ISSUE THREAD

**Issue by ElmoreaBIM** [Keboo/DotnetTemplates#143]
Resource not found 'themes/materialdesigntheme.defaults.xaml'.
I have tried many ways, but I don't get it, in fact I downloaded this template hoping to avoid this error, but it is the same error that I get to me 
Thanks in advance.

**Comment by Keboo** [comment]
Hi @ElmoreaBIM this was a breaking change with the 5.0.0 release. Check out the [migration guide](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/discussions/3466) for how to fix this. 

I am planning on getting this template updated shortly, so the next release of the templates will contain the fix as well.
